# Generated by Django 6.1 on 2026-09-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='recurring',
        ),
        migrations.RemoveField(
            model_name='income',
            name='description',
        ),
        migrations.AddField(
            model_name='bill',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Every 2 weeks'), ('monthly', 'Monthly'), ('quarterly', 'Every 3 months'), ('yearly', 'Yearly')], default=int, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Every 2 weeks'), ('monthly', 'Monthly')], default='monthly', max_length=20),
            preserve_default=False,
        ),
    ]
