# Generated by Django 6.1 on 2026-09-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_remove_bill_recurring_remove_income_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='frequency',
            field=models.CharField(choices=[('one_time', 'One time'), ('weekly', 'Weekly'), ('biweekly', 'Every 2 weeks'), ('monthly', 'Monthly'), ('quarterly', 'Every 3 months'), ('yearly', 'Yearly')], max_length=20),
        ),
    ]
